=== grandariel/tin/xml/newbooks.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT catalogue (book, publisher)>
<!ELEMENT book (title, price, ISBN)>
<!ATTLIST book
        year CDATA
        publisher IDREF>
<!ELEMENT title (#PCDATA)>
<!ELEMENT publisher (name, country)>
<!ATTLIST publisher
        abbreviation ID>
<!ELEMENT name (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price kind (retail|wholesale)>
<!ELEMENT ISBN (#PCDATA)>

=== grandariel/tin/xml/newbooks.xml
<?xml version="1.0" ?>
<!DOCTYPE catalogue SYSTEM "newbooks.dtd">
<catalogue>

    <book year="1994" publisher="AW">
        <title>TCP/IP Illustrated</title>
        <price>65.95</price>
        <ISBN>ISBN-0201633469</ISBN>
    </book>

    <book year="1992" publisher="AW">
        <title>Advanced Programming in the Unix environment</title>
        <price kind="retail">65.95</price>
        <price kind="wholesale">50.00</price>
        <ISBN>ISBN-020163346X</ISBN>
    </book>

    <book year="2000" publisher="MK">
        <title>Data on the Web</title>
        <price>39.95</price>
        <ISBN>ISBN-3343163346</ISBN>
    </book>

    <book year="1999">
        <title>The Economics of Technology and Content for Digital TV</title>
        <price>129.95</price>
        <ISBN>ISBN-433348634X</ISBN>
    </book>


    <publisher abbreviation="AW">
        <name>Addison-Wesley</name>
        <country>USA</country>
    </publisher>

    <publisher abbreviation="KA">
        <name>Kluwer Academic Publishers</name>
        <country>Holandia</country>
    </publisher>

    <publisher abbreviation="MK">
        <name>Morgan Kaufmann Publishers</name>
        <country>USA</country>
    </publisher>



</catalogue>
