=== grandariel/tin/xml/penguins.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT article (date, title, para*, source)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT para (#PCDATA|place|company|link)* >
<!ELEMENT source (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
        ref CDATA "">

=== grandariel/tin/xml/penguins.xml
<?xml version="1.0" ?>
<!DOCTYPE article SYSTEM "penguins.dtd">

<article>
<date>28/06/2000 12:30</date>
<title>Rescued penguins swim home</title>
<para><place>Cape Town</place> Some 150 penguins unaffected by the oil spill began their long swim from Port Elizabeth in the Eastern Cape back to their breeding habitat at Robben Island near Cape Town on Wednesday. </para>

<para>The penguins, who have all been tagged, were transported in a truck hired by the <company>South African National Conservation of Coastal Birds (Sanccob)</company> to Port Elizabeth on Tuesday night. </para>

<para>Its not known how many more birds will be released from Port Elizabeth after receiving treatment. </para>

<para>More than <link ref="www.newsrus.com/oilspill.html">400 tons of fuel oil escaped from the bulk ore carrier Treasure</link> before divers were able to seal the holds. </para>

<para>The ship was carrying 130 000 tons of iron ore and 1 300 tons of fuel oil when she sank off the Cape West coast last Friday. </para>

<para>A spokesperson for <company>Sanccob</company>, Christina Pretorius said the centre had a capacity to treat 1 000 penguins but presently there were in excess of 4 500 birds being rehabilitated and more would be brought to the centre on Wednesday. </para>
<source>John Rolfe</source>
</article>
